# Generated by Django 5.2.17 on 2026-09-20 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('homme', 'home'), ('femme', 'femme')], max_length=10)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('najeh', models.BooleanField(default=False)),
            ],
        ),
    ]
